question_data = {"response_code": 0, "results": [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
                                      "question": "Whistler was the codename of this Microsoft Operating System.",
                                     "correct_answer": "Windows XP",
                                      "incorrect_answers": ["Windows 2000", "Windows 7", "Windows 95"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
     "correct_answer": "C#", "incorrect_answers": ["Java", "C++", "Objective-C"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these is the name for the failed key escrow device introduced by the National Security Agency in 1993?",
     "correct_answer": "Clipper Chip", "incorrect_answers": ["Enigma Machine", "Skipjack", "Nautilus"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does the acronym CDN stand for in terms of networking?",
     "correct_answer": "Content Delivery Network",
     "incorrect_answers": ["Content Distribution Network", "Computational Data Network", "Compressed Data Network"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
     "correct_answer": "JavaScript", "incorrect_answers": ["C#", "Python", "PHP"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "In programming, the ternary operator is mostly defined with what symbol(s)?", "correct_answer": "?:",
     "incorrect_answers": ["??", "if then", "?"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is known as &quot;the brain&quot; of the Computer?", "correct_answer": "Central Processing Unit",
     "incorrect_answers": ["Motherboard", "Graphics Processing Unit", "Keyboard"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the main CPU is the Sega Mega Drive \/ Sega Genesis?", "correct_answer": "Motorola 68000",
     "incorrect_answers": ["Zilog Z80", "Yamaha YM2612", "Intel 8088"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What was the first Android version specifically optimized for tablets?",
     "correct_answer": "Honeycomb", "incorrect_answers": ["Eclair", "Froyo", "Marshmellow"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "Which of these people was NOT a founder of Apple Inc?", "correct_answer": "Jonathan Ive",
     "incorrect_answers": ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "The name of technology company HP stands for what?", "correct_answer": "Hewlett-Packard",
     "incorrect_answers": ["Howard Packmann", "Husker-Pollosk", "Hellman-Pohl"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What is the number of keys on a standard Windows Keyboard?", "correct_answer": "104",
     "incorrect_answers": ["64", "94", "76"]}]}
